### ISSUE TITLE
Message box

### ISSUE THREAD

**Issue by joetapper** [circadu/stories#11]
Not sure if this is what you meant (it's tired) but make sure the message is scrolled to see the other person's message. If it exceeds a page it should scroll to see as much as it can from the top so you don't spoil any new plot events upon scrolling up. Also is there anything to be done if a line exceeds the box space meaning you have to scroll left and right?

**Comment by samholmes1337** [comment]
Would this be an effective strategy if it is single turn based though? If there is a word limit then there is only so much they can write. Do you mean scrolling to the bottom of the last messages you saw so that you see the top-down of new content?
